dataset_name: "GSM4712885"
sample_file: "sample/sample_sheet.csv"
sample_regex: ".*"
#cell_annots: null
#cell_annots_key: "cell_id"
#exclude_unannotated_cells: False
#mouse target:utrome_mm10_v2
target: "utrome_hg38_v1"
targets_config: "extdata/targets/targets.yaml"

bx_whitelist: "/mnt/user/BXY/scAPA/SRA/human_covid_pbmc/GSM4712885/whitelist.txt"
tech: "10xv3"
strand: "--fr-stranded"
#tmp_dir: "/tmp"

min_umis: 500
output_format: "sce"
